config/routes.rb
CardGames::Application.routes.draw do
  
  resources :games do
    post 'reload' => 'reloads#reload_all'
    post 'reload_trick' => 'reloads#reload_trick'
    post 'fill' => 'fill_games#fill'
    post 'new_round' => 'rounds#create'
    post 'new_trick' => 'tricks#create'
    post 'play_one_card' => 'played_cards#create'
    post 'pass_cards' => 'card_passings#create'
    post 'toggle_passing_status' => 'card_passings#toggle_passing_status'
    post 'passing_set_ready' => 'card_passings#passing_set_ready'
  end
    
  resources :users
  
	resources :sessions
	
	match 'signup' => 'users#new'
	match 'logout' => 'sessions#destroy'
	match 'login' => 'sessions#new'

  root :to => 'games#index'
	
end

app/models/user.rb
class User < ActiveRecord::Base

  include SimplestAuth::Model
  authenticate_by :username
  
  attr_accessible :username, :password, :password_confirmation
  
  has_many :players, :dependent => :destroy, :order => "created_at ASC"
  
  validates_presence_of :username
  validates_uniqueness_of :username
  validates_confirmation_of :password, :if => :password_required?

  delegate :hand, :to => :current_player
  
  def current_player_in_game(game)
    players.where("game_id = ?", game).first
  end
  
  def is_playing_in?(game)
    current_player = current_player_in_game(game)
    current_player.present? && current_player.game_id == game.id
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url      
    else
      render action: "new"
    end
  end

  def update
    @user = User.find(params[:id])
    
    if @user.update_attributes(params[:user])
      redirect_to @user
    else
      render action: "edit"
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    session[:user_id] = nil if current_user == @user
    @user.destroy
    redirect_to root_url
  end
end

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>

  <div class="field">
    <%= f.input :username %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
  </div>

  <div class="actions">
    <%= submit_tag "Sign Up", :class => "btn"  %>
  </div>
  
<% end %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<div class="mytable">
<table class="table table-striped">
  <tr>
    <th>Username</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to user.username, user %></td>
  </tr>
<% end %>
</table>
</div>


<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Register</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<%= link_to 'Back', users_path %> | 
<%= link_to 'Delete', @user, method: :delete, data: { confirm: 'Are you sure?' } %>